### ISSUE TITLE
Compatibility issues with PHP 8.0 and 8.1

### ISSUE THREAD

**Issue by pavol-git** [Piwigo/Piwigo-SmartAlbums#18]
Is the SmartAlbums compatible with php versions newer that 7.4?  When I use newer php versions, I cannot define criteria for a smart album. Nothing happens after clicking on "This album is a SmartAlbum". After downgrading the php version, everything works as usual. However the php 7.4 is deprecated, so it is risky to use it.

**Comment by HStep20** [comment]
Im seeing the same issue, so really hope its updated soon. Smart Albums + Lightroom Tags is what made Piwigo so powerful.

**Comment by shooftie** [comment]
Is this what you are seeing? 
<img width="610" alt="image" src="https://github.com/Piwigo/Piwigo-SmartAlbums/assets/2161844/94950ae9-5b27-423b-858a-403483cc94dc">

**Comment by shooftie** [comment]
I am a FE dev who last wrote a line of php over a decade ago so I can give little support other than to describe the errors that I am seeing.

An error is occurring [here](https://github.com/Piwigo/Piwigo-SmartAlbums/blob/22cc9ddfc9575da083c36d0a2cbfba28eb26d290/admin/template/album.tpl#L244C49-L244C56) that is causing the JS to fall over on this page, also.
> Warning"
> Undefined array key "CAT_ID" in /config/www/_data/templates_c/p6j...file.album.tpl.php on line 321
> Attempt to read property "value" on null in /config/www/_data/templates_c/p6j...file.album.tpl.php on line <b>321

<img width="523" alt="image" src="https://github.com/Piwigo/Piwigo-SmartAlbums/assets/2161844/ade96cd9-a6ff-45ce-8f7f-e4173a8d9514">

**Comment by shooftie** [comment]
...and my [comment above](https://github.com/Piwigo/Piwigo-SmartAlbums/issues/18#issuecomment-1626498310) seems to be originating from around [here](https://github.com/Piwigo/Piwigo-SmartAlbums/blob/22cc9ddfc9575da083c36d0a2cbfba28eb26d290/admin/template/album.tpl#L296C5-L296C40)

**Comment by raupie** [comment]
I think the issue is here. Based on a `{$filters|@print_r}`

```Warning: Undefined array key "filters" in /config/www/_data/templates_c/8cpdn4^0bec9b5090df2ff182c443e69c156afad47ca6dc_0.file.album.tpl.php on line 386

Warning: Attempt to read property "value" on null in /config/www/_data/templates_c/8cpdn4^0bec9b5090df2ff182c443e69c156afad47ca6dc_0.file.album.tpl.php on line 386```

So this album.tpl is not getting this $filters variable or it's being sent nothing. Which makes sense, it's a brand new virtual album so it would have no "filter" created. I did only install this module yesterday so I'm not up to speed on everything.

**Comment by raupie** [comment]
Oh this is nice. I see what you are saying now @shooftie 

```
function countImages(form) {
    jQuery.post("./plugins/SmartAlbums/include/count_images.php", 'cat_id=<br />
<b>Warning</b>:  Undefined array key "CAT_ID" in <b>/config/www/_data/templates_c/8cpdn4^0bec9b5090df2ff182c443e69c156afad47ca6dc_0.file.album.tpl.php</b> on line <b>321</b><br />
<br />
<b>Warning</b>:  Attempt to read property "value" on null in <b>/config/www/_data/templates_c/8cpdn4^0bec9b5090df2ff182c443e69c156afad47ca6dc_0.file.album.tpl.php</b> on line <b>321</b><br />
&'+form.serialize(),
```

**Comment by raupie** [comment]
Last commit was 2 years ago. I'm assuming this extension is dead. I really like the idea of building "smart albums" out of existing `galleries` I've already symlink to my piwigo docker instance.

**Comment by HStep20** [comment]
It's definitely not dead - just moving slow. 

They mentioned on the [Piwigo Forums ](https://piwigo.org/forum/viewtopic.php?id=32811) that they plan to update it for php 8, but they also need to review the design of it - Which could be a part of why it isn't a big priority (especially with Piwigo 14 on the horizon).

**Comment by raupie** [comment]
I resolved the error. 

https://github.com/Piwigo/Piwigo-SmartAlbums/blob/master/admin/album.php#L392

```
$template->assign(array(
  'COUNT_SCRIPT_URL' => SMART_PATH.'include/count_images.php',
  'CAT_ID' => $cat_id,
```

I'm injecting the `$cat_id` back to the template and no more undefined array key warning. Not sure how this worked prior, did this even work before :shrug: 

Thank you for this forum link :eye:

**Comment by raupie** [comment]
MR -> https://github.com/Piwigo/Piwigo-SmartAlbums/pull/19

So far I can create smart albums and get photos to populate in them via keywords.

**Comment by shooftie** [comment]
@raupie , I'd half expected my comment to go unheard. What a pleasant surprise to find out that you're on the case!

I started out thinking, "hell, I can do this!". Alas, I couldn't even get a dev env set up.

I've been cycling through a bunch of galleries recently in the hunt for something to use and although it's not as polished as some of the _machine learning_ or _AI_ alternatives, the fact that Piwigo's attitude seems to be a bit more DIY is a major selling point for me.

Any hints on a build setup so that I can have a tinker?

**Comment by raupie** [comment]
I'm trialing piwigo for my photo organization needs. I keep coming back to it and I'm just gonna power through the bugs like this. I don't like piwigo being the "source of truth" for my photos so that was my biggest turn off but I think I can make it work through `galleries` and using symlinks to my NFS mounts that store my photos.

In regards to this bug and getting a working local dev setup working, I kinda cheated. 

I'm using linuxserver.io to run piwigo in a container. I then mounted the piwigo application over a sshfs mount point and just hacked my way and fixed it on my production environment. 

```
sshfs -o ssh_command='ssh -i ~/.ssh/id_rsa' docker@<IP>:/mnt/data/piwigo/config/www ./piwigo
```

If I want to contribute to this smartalbum extension, I'll for sure have to setup a better workflow. But I just needed to see SmartAlbum work so this is what I did and so far I'm able to create "Smart Albums" out of my "Albums" I have symlinked from my NAS NFS setup.

**Comment by shooftie** [comment]
Nice! I got as far a checking out the repo and then trying to install as much intelligence as I could to help me identify what was what. Turns out, not much.

I've got about 10 gallery solutions installed on docker in a VM and between them they either do too much or too little. I'm not after 'bells and whistles'. I am gappy to do the tagging and management myself in Digikam. I just want to be able to create smart albums and share them with family. A simple front end to my library would be amazing.

I'm subscribed to this issue now. Let's see what happens but 2y between commits feels like abandonment, to me. I am in no position to judge, however, I am sitting on a mountain of unfinished 'big ideas'.

**Comment by dd-b** [comment]
> I resolved the error.

Kinda looks like you did; at least, that same fix appears to have worked for me. Thank you!

Now, if they'd just make some progress on having this absolutely key plugin work with the current version of the software and a current version of PHP, we might have something.

Really, this should be integral functionality, not a plugin; it's utterly vital.

**Comment by plegall** [comment]
> I'm subscribed to this issue now. Let's see what happens but 2y between commits feels like abandonment, to me. I am in no position to judge, however, I am sitting on a mountain of unfinished 'big ideas'.

I agree that it's been too long since we have worked on this plugin. I made a few commits to make it more compatible with PHP 8.x and Piwigo 2.10+

We have a much deeper refresh to apply in the next months.

**Comment by plegall** [comment]
> Really, this should be integral functionality, not a plugin; it's utterly vital.

I absolutely don't agree. SmartAlbums are a nice feature, certainly not a core feature. But being a plugin feature does not mean it's a secondary level feature. It all depends on your use. Maybe for you it's a primary feature, maybe for somebody else it's not even an understandable feature.

Being provided as a plugin only means that it's not activated by default. I can tell you that SmartAlbums is not a very "popular" plugin in term of number of activation BUT it's certainly very nice/vital for those who uses it
